apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php-host
  name: php-host
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-host
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: php-host
    spec:
      containers:
      - image: zlatinov/dof-php:%PHP-IMAGE-PLACEHOLDER%
        volumeMounts:
        - name: html_volume
          mountPath: /site
        imagePullPolicy: ""
        name: php-host
        ports:
          - containerPort: 9000
        resources: {}
      restartPolicy: Always
      volumes:
      - name: html_volume
        hostPath:
        path: app/
      serviceAccountName: ""
      volumes: null
status: {}
