  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-php-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: auto-php
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auto-php
    spec:
      containers:
      - name: auto-php-container
        image: zlatinov/dof-php:%PHP-IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: auto-php-svc
  labels:
    app: auto-php
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 9000
    protocol: TCP
  selector:
    app: auto-php

    ---

